hosts: [
  { host_ip: "192.168.57.89", host_name: "cd"},
  { host_ip: "192.168.57.90", host_name: "swarm-master"},
  { host_ip: "192.168.57.91", host_name: "swarm-node-1"},
  { host_ip: "192.168.57.92", host_name: "swarm-node-2"}
]

obsolete_services:
  - puppet
  - chef-client

centos_files: [
     { src: "centos.sshd_config", dest: "/etc/ssh/sshd_config" }
  ]
